### ISSUE TITLE
Adicionar deploy de aplicação no github io

### ISSUE THREAD

**Issue by alexferreira-invillia** [alexferreiradev/gerenciador_horas_trabalho#123]
## Contexto

Hoje o usuário tem que baixar o html e rodar localmente. A ideia é ter uma versão online pelo servidor do github de forma estatica. 

## Refinamento

1. Como fazer deploy no github ? 
2. Como automatizar via actions ? 
3. Qual o tempo previsto ? 
4. Tem limitações ? 
5. Colocar link de versão estável no readme do projeto ? 
6. Tem como separar deploys ou links por ambiente ? Teria como ter uma versão dev ? 

## Tasks

- [x] Create workflow for main like: https://docs.github.com/en/enterprise-cloud@latest/pages/getting-started-with-github-pages/using-custom-workflows-with-github-pages
- [x] Test build and deploy
- [x] Test main features
- [x] Test redirect
- [x] Configure workflow to be auto when PR merged in main

**Comment by alexferreira-invillia** [comment]
Draft Refinamento: 
https://docs.github.com/en/enterprise-cloud@latest/pages/getting-started-with-github-pages/creating-a-github-pages-site

**Comment by alexferreira-invillia** [comment]
Gerar url para env stage diferente de prd.

Uma forma que encontrei foi com este artigo: https://dev.to/mktcode/multiple-environments-with-github-pages-53me

**Comment by alexferreira-invillia** [comment]
Vamos deixar com o deploy atual. Se ficar ruim, criamos um bug.
